### ISSUE TITLE
[Bug] Starting Storeman 0.3.0-1.12.1 on Jolla Tablet (i486) causes app closing

### ISSUE THREAD

**Issue by explit7** [storeman-developers/harbour-storeman#287] opened 2022-04-01 21:53 UTC
**SailfishOS VERSION** (Settings → About product → Build): 4.4.0.58
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): Jolla Tablet JT-1501 
<br />**Storeman VERSION** (Storeman → [Top pulley] About Storeman): 0.3.0.-1.12.1
<br />

#### BUG DESCRIPTION
If Storeman 0.3.0.-1.12.1 is started on the Jolla Tablet (i486) from the UI -> App starts but closes after some seconds.
If Storeman is started via terminal -> it starts normal

If i remove Sandboxing=Disabled from the .desktop file and start it from the UI -> it starts normal and doesn't close, but hangs on Initialising.

So the problem has something to do with Sandboxing...

#### STEPS TO REPRODUCE
Storeman 0.3.0.-1.12.1 is started on the Jolla Tablet (i486) from the UI -> App starts but closes after some seconds.

#### ADDITIONAL INFORMATION

--

**Comment by Olf0** [comment] 2022-04-01 22:35
Well, this is more or less a duplicate of issue #236 "[Define, implement and test a proper SailJail "profile"](https://github.com/storeman-developers/harbour-storeman/issues/236)".

I have no idea why trivially bailing out of Sailjail via `Sandboxing=Disabled` does not seem to work on i486.

**Comment by snm247** [comment] 2022-07-20 17:46
Not sure if this is helpful, but on my Jolla Tablet Storeman is working without problems so far (started from the UI).

SailfishOS version 4.4.0.68
Storeman 0.3.1
Jolla Tablet JT1501

Also since I'm one of the few Jolla Tablet owners, feel free to ping me if there is something to test.

**Comment by Olf0** [comment] 2024-03-23 19:09
@explit7, does this issue still persist on your Jolla tablet?

If not, please close this issue; if it still does, please denote that in a comment ("This still is an issue" is sufficient).

**Comment by explit7** [comment] 2024-03-23 19:56
Thanks, the problem is solved. can be closed

**Comment by Olf0** [comment] 2024-03-23 21:28
> Thanks, the problem is solved.

Just curious: Did "it solve itself" (i.e. it was fine after some Storeman or SailfishOS upgrade), or did you do something to resolve it?

I am asking, because the fact @snm247 cannot reproduce this issue on his Jolla tablet, makes it likely that there is (or "was") something special / wrong with the specific Storeman or SailfishOS installation you use.

**Closed by Olf0** 2024-03-23 21:28 UTC
Labels: bug, help wanted

**Comment by explit7** [comment] 2024-03-24 02:04
It was fine after update
