### ISSUE TITLE
Fails to install Storeman when not logged in to Jolla account

### ISSUE THREAD

**Issue by delight-aug** [storeman-developers/harbour-storeman#159] opened 2022-02-15 01:21 UTC
Hi! I've just installed Sailfish OS on Xperia 10 but skipped logging into Jolla's account. Then I proceeded to download and install Storeman Installer. But when I launched it, it started spinning for a bit and closed itself without reporting any problems. I've tried a few more times, but no luck. Then, I've logged into my Jolla account and chose to download recommended apps. Then, as one of them was installed, I launched Storeman Installer and it worked this time.

**Comment by Olf0** [comment] 2022-03-02 04:04
Except for the last two sentences, this sounds like a duplicate of https://github.com/mentaljam/harbour-storeman-installer/issues/1
If this issue is about Storeman Installer, it should be filed there.

But the you write *"I launched Storeman and it worked this time."*, but you failed to run the its Installer: That does not make sense to me.
Maybe some information is missing, please clarify.

**Comment by delight-aug** [comment] 2022-03-02 07:10
> But then you write "I launched Storeman and it worked this time."

I meant Storeman Installer, sorry. Edited now

> Except for the last two sentences, this sounds like a duplicate of https://github.com/mentaljam/harbour-storeman-installer/issues/1

It probably is. I have no further information, and I'm already moved back to Android.

**Comment by Olf0** [comment] 2022-03-02 18:09
O.K.  Thank you for rectifying your statement.

**Comment by Olf0** [comment] 2022-03-13 06:04
**SailfishOS VERSION** (Settings → About product → Build): ¿4.3.0.12?
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): Xperia 10
<br />**Storeman VERSION** (Storeman → [Top pulley] About Storeman): Noine, but Storeman Installer ¿v1.0.1?

**Closed** 2022-03-17 00:17 UTC
Labels: duplicate
