### ISSUE TITLE
[Bug] Page "Local RPM files" does no longer work

### ISSUE THREAD

**Issue by citronalco** [storeman-developers/harbour-storeman#461] opened 2024-03-12 11:56 UTC
**SailfishOS VERSION** (Settings → About product → Build):  4.5.0.24
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): Sony Xperia X Compact
<br />**Storeman VERSION** (Storeman → \<Top pulley\> → About Storeman): 0.3.1
<br />

#### BUG DESCRIPTION
Page "Local RPM files" does no longer work. 

#### STEPS TO REPRODUCE
Open "Local RPM files". "Page could not get loaded" gets displayed.

#### ADDITIONAL INFORMATION
Console output:
```
QML AnimatedLoader: (file:///usr/share/harbour-storeman/qml/pages/LocalRpmsPage.qml:3:1: module "QtSparql" is not installed
    import QtSparql 1.0
    ^)
```
libqtsparql is installed.

Seems to be caused by this change: https://github.com/sailfishos/libqtsparql/commit/f543a9d332df50d66fbeac18dcded34cca92a2a0

**Comment by Olf0** [comment] 2024-03-12 16:38
@citronalco, thank you very much for this issue report and analysis.

I reported it to @pvuorela here: https://github.com/sailfishos/libqtsparql/commit/f543a9d332df50d66fbeac18dcded34cca92a2a0#commitcomment-139687738

**Comment by pvuorela** [comment] 2024-03-14 07:31
QtDocGallery might work on older releases. There were some adjustments, but think it was more on needing to define proper root type to match the graph. Above should be fine. I guess the new tracker version came with 4.3.0.

**Comment by pvuorela** [comment] 2024-03-14 16:44
It's a balancing act. On one hand making changes can break things elsewhere, but on the other hand keeping backward compatibility can also be an accumulating maintenance burden, eventually slowing down the development. Also often the changes are done because the old api was just somehow bad, perhaps being good enough for the internal feature it was developed for, or maybe done or inherited from somewhere without actually having real-life application proving it's fit for the purpose.

But I'm noting your comment and perhaps we can still bring back the qml api.

**Comment by Olf0** [comment] 2024-03-14 18:20
> It's a balancing act. …

Sure, I only want to point out the scope and lasting, dire consequences this regularly has, because I repeatedly had the impression that Jolla does not take the SailfishOS' app ecosystem (i.e. outside of the Jolla Store) seriously into account when considering breaking changes.

> On one hand …

All agreed, but this is a purely technical and Jolla-internal point of view.  It does not take into account frustration of users (apps do not work any longer after an SFOS upgrade), developers (Jolla broke my app again, so I have to invest time) and developer brain drain (there are less and less around due to aforementioned reasons).

> But I'm noting your comment and perhaps we can still bring back the qml api.

Well, I do not think this is necessary any longer due to your kind help.  And the breakage is already done by SFOS 4.5.0 WRT libqtsparcl's QML API and SFOS 4.3.0 WRT the tracker API.

I would really appreciate if you mind the big picture I tried to draw with that comment when performing the "balancing act" of introducing breaking changes and / or  investing effort into designing APIs: IMO one should always design APIs as thoroughly as if they have to last forever (e.g. extensible; there always will be users soon, you do not know about), because non-backwards-compatible API changes will likely break some software.

**Comment by citronalco** [comment] 2024-03-14 21:04
Guys, I'm also no programmer. Yesterday was the first time I ever installed Sailfish SDK and saw a QML file.

Install the Sailfish SDK (if you want to test the app on older Sailfish OS versions, simply enable that versions as "Target" and "Emulator", too).
Then clone the harbour-storeman repo, open the "harbour-storeman.pro" in Sailfish SDK and click the green play button on the lower left. You can switch to another Sailfish OS version with the "Debug" button on the lower left and pick the wanted "Device".

You can even connect with ssh (given you've installed Sailfish SDK in ~/SailfishOS):
```
ssh -p 2223 -i ~/SailfishOS/vmshare/ssh/private_keys/sdk defaultuser@localhost
ssh -p 2223 -i ~/SailfishOS/vmshare/ssh/private_keys/sdk root@localhost
``
If you have more than one emulator VMs, the next VM listens on port 2232 (at least that's what it did here)

It's not that difficult, pvuorela nearly posted the solution. The rest is searching on Stackoverflow and Github for similar code.

I had to increase the RAM size of the "Sailfish SDK Build Engine" VM in VirtualBox to get rid of "out of memory" errors while building.

**Comment by Olf0** [comment] 2024-03-15 00:29
><sup>Guys, I'm also no programmer.</sup>

<sup>Oh, sorry; because you posed the PRs based on @pvuorela's suggestion for the two ISOdrive forks so promptly and apparently profoundly, I expected you to be way ahead in the learning curve.</sup>

<sup>Well, decades ago I was a mediocre C-for-microcontrollers programmer and know UNIX shell programming quite well (and still like it).  But employments have led me first to teaching UNIX inside out (including shell & C: Solaris, HP-UX, AIX, IRIX and Linux) and later away from hands on technical stuff to IT project management and IT security, then ultimately to IT policies and legal aspects of IT, data processing and FLOSS.  I forgot so many things over the years and was only able to keep my shell scripting skills up.</sup>

><sup>Yesterday was the first time I ever installed Sailfish SDK and saw a QML file.</sup>

<sup>Oh, wow!  While I have never installed the SFOS-SDK (and probably never will), I have looked at many QML files over the past decade (i.e. due to using SailfishOS), but still do not comprehend much, which is likely caused by the fact that I do not like JavaScript.</sup>

><sup>Install the Sailfish SDK …</sup>

<sup>Here I do refrain, I employ [GitHub workflows with Coderus' SFOS-SDK docker images](https://github.com/storeman-developers/harbour-storeman/tree/devel/.github/workflows) for compiling stuff.
You know … "modern" … "in the Cloud" and … "with containers". :wink:</sup>

@citronalco, thank you very much for your PR #462!  AFAICT, this is looking good.  I suppose you have started the resulting binary and a quick test has shown the "Local RPM files" page to work well?

When looking through the changes PR #462 brings, two things came to my mind:
1. I realised that the old `query` line, which uses `libqtsparql`'s QML API, looks much alike an SQL statement:
   `query: "SELECT str… as ?filePath WHERE { …:mimeType 'application/x-rpm' }"`
   Hence I asked myself, "Which database does this use?" and searched the WWW for `sparql`: [Wikipedia nicely provides a structured explanation](https://en.wikipedia.org/wiki/SPARQL) of SparQL, basically stating that it allows to query RDF information by SQL-like statements.
   But with `libqtsparql` the structured information which can be queried are Qt objects: That is indeed very cool!
   
   @pvuorela, as I denoted before, the breakage is done, hence restoring `libqtsparql`'s QML API does not really automatically reverse that (and you did not like its old QML API: *["the qml options usage from c++ was strange"](https://github.com/sailfishos/libqtsparql/commit/f543a9d332df50d66fbeac18dcded34cca92a2a0)*), but now I see how versatile and elegant (and impressively cool) the capabilities of `libqtsparql` are: Hence it really might be worth considering to expose `libqtsparql` to QML again.
2. Following @pvuorela' suggestion, [we now look for the file extension `rpm` / `RPM`](https://github.com/storeman-developers/harbour-storeman/pull/462/files#diff-0e58c25f77f5dc0073882d9cb45aa579b9226d79966de69f6c650bd60042c220R19-R26).  But IMO querying for files whose `mimeType` is `application/x-rpm` is much more elegant, as the original code did.  So I tried to determine how this might be achieved, unfortunately to no avail: There is no documentation for `QtDocGallery` at [`doc.qt.io`](https://doc.qt.io/), because it is marked as "experimental", and [the `doc` directory in the source tree contains nothing useful](https://code.qt.io/cgit/qt/qtdocgallery.git/tree/doc/src) (only stubs).  The furthest I could get was via a [code browser, which resolves the header files](https://codebrowser.dev/qt5/qtdocgallery/src/imports/gallery/), but there my knowledge how to proceed ends.
  <sub>Side note: I was surprised to see that [`QtDocGallery`'s development basically ceased 10 years ago](https://github.com/qt/qtdocgallery/commits/master/), but then I searched for `libqtsparql`'s documentation an all I found was once on "NOKIA developers" for MeeGo 1.2 Harmattan: [[1]](https://n9.dy.fi/meego/html/libqtsparql/main.html?tab=1) and [[2]](https://n9.dy.fi/meego/html/libqtsparql/classQSparqlQuery.html?tab=1)!  O.K., now I see why `QtDocGallery` ranks better and basically it is you @pvuorela who maintains both, AFAICS.  Kudos!</sub>
   
   If you @pvuorela can think of a way how to query files for `mimeType: 'application/x-rpm'`, please denote that, if not, do not invest much effort.  Even though relying on file extensions is "so 90ties" rsp. (worse) "so Windows", this basically works, but is just ugly.
   Thank you for all your kind advice and efforts.

**Comment by citronalco** [comment] 2024-03-15 00:37
It works at least in Sailfish OS 4.5 and 3.4. Tested that in the emulator VMs provided by the SDK.

**Comment by pvuorela** [comment] 2024-03-15 08:45
> @pvuorela, as denoted before, the breakage is done, hence restoring libqtsparql's QML API cannot reverse that for the SailfishOS releases made meanwhile (and you did not like its old QML API: ["the qml options usage from c++ was strange"](https://github.com/sailfishos/libqtsparql/commit/f543a9d332df50d66fbeac18dcded34cca92a2a0)), but now I see how versatile and elegant (and impressively cool) the capabilities of libqtsparql are: Hence it really might be worth considering to expose libqtsparql to QML again.

Still considering that indeed. Tracker sparql allows to search for many things, but it can be also tricky to get right sometimes, and the data, query details etc have been changing so QtDocGallery has been there for easier to use model.

> Side note: I was surprised to see that [QtDocGallery's development basically ceased 10 years ago](https://github.com/qt/qtdocgallery/commits/master/), but then I searched for libqtsparql's documentation an all I found was once on "NOKIA developers" for MeeGo 1.2 Harmattan: [[1]](https://n9.dy.fi/meego/html/libqtsparql/main.html?tab=1) and [[2]](https://n9.dy.fi/meego/html/libqtsparql/classQSparqlQuery.html?tab=1)! O.K., now I see why QtDocGallery ranks better and basically it is you @pvuorela who maintains both, AFAICS. Kudos!

Thanks. Yea, basically the upstream development stopped at some point and ours if the de facto upstream now.

> If you @pvuorela can spontaneously think of a way how to query files for mimeType: 'application/x-rpm', please denote that, if not, do not invest much effort. Even though relying on file extensions is "so 90ties" rsp. (worse) "so Windows", this basically works, despite being ugly.

I think it should work just by using 'mimeType' property instead of the 'fileExtension'. In practice the result should be the same and don't recall even seeing that much capital RPM extensions ever.

**Comment by Olf0** [comment] 2024-03-17 20:01
I have found documentation for `DocumentGalleryModel` in the "[Qt Mobility 1.2.2 Project Reference Documentation](https://doc-snapshots.qt.io/qt-mobility/index.html)":
* Overview of [Document Gallery](https://doc-snapshots.qt.io/qt-mobility/gallery.html) Elements (Filters etc.)
* [QML `DocumentGalleryItem` Element](https://doc-snapshots.qt.io/qt-mobility/qml-documentgalleryitem.html)
* [QML `DocumentGalleryModel` Element](https://doc-snapshots.qt.io/qt-mobility/qml-documentgallerymodel.html)
* [QML `DocumentGalleryType` Element](https://doc-snapshots.qt.io/qt-mobility/qml-documentgallerytype.html)

**Closed** 2024-03-18 19:59 UTC
Labels: bug

**Comment by Olf0** [comment] 2024-03-19 00:22
Thank you both, @citronalco and @pvuorela very much, both variants are working fine: As @citronalco already tested on SailfishOS 4.5.0 and 3.4.0, I just additionally tested both variants on SailfishOS 3.2.1.

For the diff between the two variants, see commit 56eabea.

**Comment by Olf0** [comment] 2024-03-19 14:20
@citronalco, if you would like to perform a final test of the release version of Storeman 0.3.8, you can either use [the one(s) compiled by the GitHub workflow(s)](https://github.com/storeman-developers/harbour-storeman/releases) or [the "testing" ones at the SailfishOS-OBS](https://build.sailfishos.org/project/show/home:olf:harbour-storeman:testing).  Actually I am also interested to know if [the RPM files compiled at GitHub with the Sailfish-SDK for SailfishOS 4.2](https://github.com/storeman-developers/harbour-storeman/releases/tag/release1_sfos4.2%2F0.3.8#js-repo-pjax-container) run on SailfishOS 4.5.0; if the unpacked RPM files do not work, the ones inside the ZIP archive compiled for 4.5.0 should.

Note that the Storeman Installer currently still fetches [Storeman 0.3.7 from the SailfishOS-OBS](https://build.sailfishos.org/project/show/home:olf:harbour-storeman).
